### PR TITLE
Proposed Changes

### PR DESCRIPTION
**Pull request by rpaladin**
Hi. I noticed a few uncaught issues and unneeded elements.
Proposed changes can be previewed here:

<hr />

# Global

1. Remove URL extensions from all navbar-webpage related links to improve professional look
e.g. `community.html` -> `community`
2. Removed homepage from navbar, as we already have navbar icon/text buttons'
3. Add navbar icon/text buttons' to mobile nav
4. Add `www.` extension to all links that are not asset-related sources

# index.html

1. Change homepage link from `index.html` to `/` to avoid exposing unnecessary paths
2. Remove unnecessary white-space at line 58

# news.html

1. Fix Twitter URL to appropriate  standard

# community.html

1. Implemented 5 new community links - priority orders are moot
2. Fix Discord invite link to appropriate standard
3. Change text `Forums` to `Forum`, as the forum itself is not plural, but rather sub-forums

<hr />

~~1. I'd like to apologize in advance if changes are only meant to be limited to  root `.html` files and not `build` files too.~~
2. Additionally I had some Workflow errors but I believe that they are relatively minor/unrelated.
3. I would also like to also propose a overhaul of the website to include a JS approach, one that I have already have already successfully implemented in the past:
<https://github.com/rpaladin/UPBGE-Website-Forks/blob/JS/index.html#L23-L56>
This approach would piece together the navbar + footer PER webpage dynamically on page load, thus reducing reptition and wasted time as a developer will only need to edit in one location for all of the webpage children.
4. Finally, as discussed in the Armory Discord, perhaps we should remove the `News` section all together as we already have the `Release Notes` section.

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
Nice!

> Remove URL extensions from all navbar-webpage related links to improve professional look
e.g. community.html -> community

I'm not sure if it's worth it, if you now open the page locally the links no longer work (at least on Firefox).

> 1. I'd like to apologize in advance if changes are only meant to be limited to root .html files and not build files too.

The naming of the build folder might be misleading here, but that's actually the source folder. If you have a look at build/make.js which you can call with node.js, you will see that it's a very basic template system where each file in the build folder automatically gets its header and footer – so we already have a static solution for your 3. point and those template files shouldn't have a header and footer. Feel free to add it to the readme :)

**Comment by rpaladin** [comment]
> I'm not sure if it's worth it, if you now open the page locally the links no longer work (at least on Firefox).

This is true, but respectfully unrelated as most web developers developing under localhost conditions.
Else their page structures will break or not work sometimes.

A person can easily host a local server with Python, Node.js, or Apache - note with Apache you'll need to allow `mod_rewrite` in your `conf/http.conf` file.

Even Visual Studio Code has several downloadable extensions for hosting a local server.

In fact I wouldn't be surprised if you were able to tweak the Armory3D localhost source to be your go to server host choice for web testing.

> The naming of the build folder might be misleading here, but that's actually the source folder. If you have a look at build/make.js which you can call with node.js, you will see that it's a very basic template system where each file in the build folder automatically gets its header and footer – so we already have a static solution for your 3. point and those template files shouldn't have a header and footer. Feel free to add it to the readme :)

Things seem much clearer now. Will be sure to propose new changes for the readme!

<hr />

Thanks for the feedback. Will revert the changes later today or tomorrow when I'm more free.

**Comment by MoritzBrueckner** [comment]
It's luckily not up to me to decide this :) I just don't see a reason to make things more complicated for the sake of a more professional looking URL, the Armory website is not more than a bunch of static html files. The good thing however is that the site is so simple that you don't even need to click the links in the header when testing locally, you can simply open the other files. So still no server required here, it's just a minor inconvenience and I can get along with both ways.

Looking forward to the new changes!

**Comment by rpaladin** [comment]
1. Added appropriate new content to `header.html` & `footer.html` in the `build` folder.
2. Reverted changes to all the other build pages.
3. Added changes to both `README.md` files to explain how to properly commit to the repository for newcomers.

**Comment by rpaladin** [comment]
Hi and sorry to disturb you @luboslenco.
I understand you are very busy with several commitments and projects.

My PR I believe contains the final implementations of the suggested changes from above.
If you believe the proposals are unnecessary or have any different suggestions/thoughts feel free to do so, I do not mind.

**Pull request merged**
