### PR TITLE
Proposed Changes #2

### PR DESCRIPTION
**Pull request by rpaladin**
# Real-Time Preview

* <https://rpaladin.github.io/>

# Requests for Lubos

1. Delete `master` branch
2. Rename `gh-pages` branch to `master`
3. Fix Website link(s) indexing for Google searches (most are outdated)
Docs: <https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl>
4. The new 404 webpage works well for my domain user domain (rpaladin.github.io).
The `armory_web` repository however, is not hosted on the `armory.github.io` domain but rather a custom domain, which may require the manually stating of it on Github.
Docs: <https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site>

<h1 id="placeholder">Questions for Lubos</h1>

1. Should the Fund & Download pages be moved under one dropdown category, or kept as separate buttons?
2. Should the navbar-text (near navbar-icon) be kept named as `Armory3D`, or changed to `Armory 3D Engine` (like the api), `Armory 3D`, or even `Armory`
3. Which color is best for the navbar download button do you think. Blue, red, etc.

<hr />

# README.md

* Improved information, grammar and markdown

# Global

* Migrated `FeaturedCover.jpg` from `header.html` (now contributor must add per-webpage)
This is to prevent it from showing in the new `404` webpage and taking up 75% of the error screen :P

# style.css

* Implemented new `ro-navbar-light` class for new navbar dropdowns

# 404.html

* Implemented new `404 webpage`

# build folder

* Renamed `build` folder to `templates` for clearer clarification

# make.js

* Tweak for new `404` webpage + cleanup `grammar`

# header.html

1. Fix proper CSS type statements
2. Implemented `homepage switcher` for both large-screen & mobile-screen + cleanup mobile navbar links
3. Tweaked `color`, `mode`, `timeout` values, `margin`, etc.` for both large-screen & mobile-screen
4. Implemented new categorized `dropdown menus` for links
5. **Note:** large-screen dropdown menus open on `hover`, while mobile-screen dropdown menus open on `click`
6. Migrated a few buttons to `sub-menus`

# footer.html

1. Removed redundant links
2. Implemented several new links

# index.html

* Removed `www.` from ArmoryPaint + ArmoryLab links to avoid getting security alert message

# community.html

1. Removed redundant links
2. Implemented `Artstation` link
3. Changed priority-order for some links
4. Implemented `www.` extension to all links that are not asset-related sources
5. Improved markdown, grammar

# fund.html

* Removed `www.` from ArmoryPaint links to avoid getting unsecure security alert message

# notes.html

* Removed redundant "Footer Content" comment

<hr />

# Special Thanks

* I'd like to especially thank @MoritzBrueckner for lending his eyes and time.

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
That's awesome! I really like the hover effect for the menu entries!

> Should the Fund & Download pages be moved under one dropdown category, or kept as separate buttons?

I'm not Lubos, but I would like to propose yet another solution: the download page has not much content, and it could work to move the content from the fund page onto the download page and thus combine both pages (and maybe even redesign the combined page so that the user directly sees both the download embed and the possibility to donate). But I guess the menu is already much clearer than before so a separate fund page also looks ok to me.

A few little things that I noticed:
- Upon reloading the page or changing pages, the website layout flickers and looks wrong for a tiny amount of time. It's not a big problem, but maybe there is a simple solution for this?
  <details>
    <summary>Click to see the flickering image</summary>
      
    </summary>
  </details>
- What do you think about adding a hover effect to the download button in the navbar? Currently the only thing that changes is the mouse cursor.
- Can the clickable area for navbar entries be enlarged so that it spans the entire height of the menu bar (or at least a larger vertical area)? It's easy to overshoot the text with the mouse and then you have to readjust it in order to be able to click or hover the entries.

**Comment by rpaladin** [comment]
> Upon reloading the page or changing pages, the website layout flickers and looks wrong for a tiny amount of time. It's not a big problem, but maybe there is a simple solution for this?

Yes I noticed that too. It's due to the dropdown menus being initially unhidden on load.
The ArmorPaint also reproduces the issue for its Website Switcher dropdown menu.
Most noticeable at the [Cloud webpage](https://armorpaint.org/cloud.html).

Watch the top-left while the webpage is refreshed repeatedly by me.
https://user-images.githubusercontent.com/69180012/159083012-e2712984-859c-420e-a652-6fe38be6eeea.mp4

I think I can fix the issue though. I'll work on that.

> What do you think about adding a hover effect to the download button in the navbar? Currently the only thing that changes is the mouse cursor.

I thought of implementing it. But than I noticed that the [Unity3D](https://unity.com/) website has no hover effect for their download (`Get started`) button which lead me to believe it was unneeded.

image

> Can the clickable area for navbar entries be enlarged so that it spans the entire height of the menu bar (or at least a larger vertical area)? It's easy to overshoot the text with the mouse and then you have to readjust it in order to be able to click or hover the entries.

Could you share me an screen of what you're describing? I'm having some trouble visualizing which area you're describing.

<hr />

Finally, thanks for the input! Much appreciated.

**Comment by MoritzBrueckner** [comment]
> Could you share me an screen of what you're describing? I'm having some trouble visualizing which area you're describing.

This is the current hitbox for the menu entries:
grafik

I'm wondering if the following would be better:
grafik

It's basically [Fitts' law](https://en.wikipedia.org/wiki/Fitts%27s_law): if your mouse cursor is somewhere over the page and you move it vertically to go to the menu bar, it is likely that you will overshoot the target if your mouse movement is sufficiently fast, because the target height is relatively small. With a larger hitbox you have more room for potential "mis-target" errors.

I'm not sure though how common and desired it is this way, maybe somewhere in between (but close to the second screenshot) is already sufficient.

**Comment by rpaladin** [comment]
# Real-Time Preview

* <https://rpaladin.github.io/>

# README.md

* Improved grammar

# Global

* Fixed loading glitches

# CSS

* Removed unused proposed styles

# header.html

1.  [global] Improved `formatting`
2.  [global] Fixed button `highlighting` bug
3.  [global] Renamed `DOCUMENTATION` categories titles to `LEARN`
4.  [global] Implemented `Tutorials` link under `LEARN` navbar categories
5.  [global] Gave `LEARN` category links higher priority over `SHOWCASE` category links
6.  [global] Partially-reverted `proposed styles` due to potential & unavoidable complications
7.  [global] Implemented `dark theme` for scroll-bars
8.  [large-screen] Implemented unique `download icon` for download button
9.  [mobile-screen] Implemented old style `download` button
10. [global] Added `dividers` for all `dropdown menus`
11. [global] Added `border`(s) for all `dropdown menus`
12. [global] Corrected `border alignment` for `dropdown menus` (except menu switcher menu due to issues)
13. [mobile-screen] Improved `mobile-screen` -> `menu icon`

# footer.html

* Migrated `scripts` to `header.html`

**Comment by rpaladin** [comment]
> Sounds fine to me as well!

> I like the red one, so it also matches with the itch.io download widget. What do you think?

Hm, these two subjects actually contradict each other a bit, as having a unique download button somewhat ruins the affect of a dropdown button that can be seen with the other navbar buttons.

Should we perhaps remove the idea of a unique button for Download and/or Fund and replace it with an average navbar button?

> Should be ok as is with Armory3D, with first content paragraph then being Armory 3D Engine.

Makes sense. Thanks for the reply!

**Comment by MoritzBrueckner** [comment]
> Hm, these two subjects actually contradict each other a bit

Do they? To me it sounds as if one question was about merging the funding page into the download page and the other one was about the button that leads to the download page. So we could have a red download button that leads to the download page where there is also a section on funding.

**Comment by rpaladin** [comment]
> To me it sounds as if one question was about merging the funding page into the download page and the other one was about the button that leads to the download page.

Ah maybe I misunderstood.. I was under the impression you wanted a dropdown menu to replace the Download button, which would also include the Fund button under the dropdown:

image

Perhaps you/Lubos was referring to literal combining of HTML source for both `download.html` & `fund.html` ?

**Comment by rpaladin** [comment]
# Updates
1. Migrated `fund.html` content to `download.html`.
2. Changed download button color(s) to `red`.
3. Changed footer `Kha` link to `Kode` as it's the parent of Haxe, Kha, Krom, etc.
4. Major typo code cleanup. A few by me, several in `notes.html` by @Naxela ❤️ (we all mess up sometimes)
P.S. Aways check that you're not pasting code typos! And please also remember to add alt attributes for img tags.
5. Removed some outdated HTML or replaced with current code rules.

# New Questions for Lubos
* Would it be alright to migrate the UIKit CSS files to the Github repository to reduce extra HTTP requests?
Or is there perhaps some unknown reason they're residing in external CloudFlare servers.

* Or if you're still hesitant to the idea of that, perhaps you'd prefer still using the official UIKit CDN links listed at their download page, but more up-to-date than the ones currently used for the website:
**UIKit v1:** https://getuikit.com/docs/installation#download
**UIKit v2:** https://cdnjs.com/libraries/uikit

* Is the current website using UIKit v1 or UIKit v2?
I believe it's using v2, but wanted to double-check with you.

# Final
* If this PR is believed ready to merge, could you consider implementing 2 (if not all 4) of the original Lubos requests stated in my original PR post. Thank you!!

**Comment by Naxela** [comment]
@rpaladin 

Hi,

Thanks for the code clean-up. Do you have any specific typos that gets repeated in the notes.html? - Since I'm using a script to auto-generate the notes, and just to prevent that the typos become redundant it's just as well to have it fixed in the auto-script once I'm at it

**Comment by rpaladin** [comment]
@Naxela 

> Do you have any specific typos that gets repeated in the notes.html?

https://github.com/armory3d/armory_web/pull/15/commits/39c1a1acefd4ca95e201900a21c6850ba70d88da#diff-edf678be2313d5f4b8196db3c3589e20b5609825f3ec0178f2e1f80e32b78bf1

# `templates/notes.html` (OLD)

### Accidental closing `</a>` tag with no opening tag.
Probably implemented while pasting:
- Line 279
- Line 281
- Line 287
- Line 372
- Line 382
- Line 447
- Line 448
- Line 449
- Line 450
- Line 551
- Line 457
- Line 463
- Line 464
- Line 538
- Line 544

# Missing `</div>` elements (NEW) `templates/notes.html`
- Line 77 is missing closing div
- (last-line) Line 1012 is missing closing div

# Side Requests
- In the future, would you possibly consider naming my contributions as `RPlaladin` and not `Rpaladin`? Thanks!
I have already fixed it for your previous notes PR so no need to go back and fix those commits, but for future notes commits that would be great!

# A Humbly Shared Tip
- Use a HTML validator in the future to help track down potential typos/code-deprecations/errors:
https://validator.w3.org/
**NOTE:** The service will always raise some errors because of the UIKit framework classes - this is unavoidable but in the long term it doesn't hurt to double-check one's work.

**Comment by luboslenco** [comment]
> Would it be alright to migrate the UIKit CSS files to the Github repository to reduce extra HTTP requests?

Yes! I think the reason is that it was just done that way by Rovacado who greatly upgraded the armory website a while ago.

**Comment by rpaladin** [comment]
Migrated external UIKit links/file to local & relative-paths.

Humble request again, requests for Lubos: https://github.com/armory3d/armory_web/pull/15#user-content-placeholder

**Comment by luboslenco** [comment]
Happy to merge when ready. Will also check on the 404 webpage once in.

**Comment by rpaladin** [comment]
Hi, sorry the recent spam.. there was a lot of confusion and some fixed conflicts relating to the `master -> main` branch switch on my end. I also accidentally created a new PR, #18 but closed it. Please ignore it :-)

Despite no visible commit activity above, I have successfully merged/commited @Naxela awesome changes. Commit diff for this PR should show everything is up to date and resolved.

**Comment by luboslenco** [comment]
No prob at all! There appears to be a merge conflict with `build/notes.html` and `notes.html` files, should I check on that?

**Comment by Naxela** [comment]
@rpaladin
Is it possible to just overwrite the notes.html with the fixes you've made (Since your version is the more W3C correct version)?

**Comment by rpaladin** [comment]
> @rpaladin Is it possible to just overwrite the notes.html with the fixes you've made (Since your version is the more W3C correct version)?

Yes it definitely is. If @luboslenco agrees to force merge this PR, @Naxela your latest 2022.5 changes will be kept, as I already migrated manually all of the changes to my modified, alternate version. The only remaining conflicts are the fixes and shouldn't break anything, as can be seen in the preview link I shared above.

By the way, I forgot to thank you for still maintaining the notes. Thanks for those!

**Comment by luboslenco** [comment]
Thanks! Merged at https://github.com/armory3d/armory_web/commit/6628571e326a369fa737e5c643d2e1312f54d9e4 via command line, let me know if I missed something.

**Pull request closed without merging**
