### PR TITLE
 Update release notes to 2023.01 / misc changes

### PR DESCRIPTION
**Pull request by rpaladin**
# 🔨 2023.01 - Happy New Year!! 🔨

Hi Lubos, Naxela was busy this month with holidays / work and asked me to sub for him.
PR Preview: https://rpaladin.github.io/notes#2023.01

# 📜 CHANGELOG

## 🚀 NEW
- [NAVBAR]: Implemented new link for forum resources/tutorials category. Originally requested [here](https://forums.armory3d.org/t/solved-a-separate-resources-category-for-only-free-engine-game-resources/5079/3).
- [NOTES]: Implemented new release notes (2023.01).

## 🎉 FIXED
- [NOTES]: Fixed incorrect grammar.
- [GLOBAL]: Cleanup whitespace.

# ❔MISC QUESTIONS

A few questions relating to what was said in #34 if you have a moment.
1. Regarding the back-porting of the manual (team decision) back to individual Markdown files, would you prefer a separate repository, for instance the [old documentation repository](https://github.com/armory3d/armory_docs), where we could use something like a fancy `docs.armory3d.org` domain (if it doesn't cost too much), or would you prefer to keep the manual in a [relative folder](https://github.com/armory3d/armory_web/tree/main/manual)?
2. Would do you think about creating a Armory3D marketplace? Several members of the community have requested one, but there's been some speculation on whether it would be logical decision in terms of maintenance / professional quality. Unrelated, Godot's [Asset Library](<https://godotengine.org/asset-library/asset>) is hosted on Github, and we could as well for no cost. We could also probably integrate with the Armory add-on / Blender if we created one.

### CODE REVIEW

**Comment by luboslenco** [comment]
Super cool, thanks again!

1. Happy with either one, let me know which one do  you prefer.
2. Might be cool, happy to merge that if someone is willing to maintain it. 🙂

**Comment by Onek8** [comment]
I am actually currently working with a commercial client on a Actix web shop handling 16k+ items in real time filtering  which I am willing to host an instance for us. I purchase a server, you can point a subdomain, and on github someone can manage the products file as basically the entire database. Formatted as such (first row definitions, all other rows are individual products like csv)

title;image;author;description;email;website;price;paypal;sdk_compatability;ect..
FPS Shooter;https://somewhere.com/items/assetIMG.jpg;Sir James the Great;sirj@gmail.com;Complete FPS kit to get your game started.....;

It is no burden for me other then a 5$ vps somewhere. I plan on making many assets myself so I am sure that fee will cover itself. I also have plans on making a p2p serverless webassembly shop reusing some of my code which is planned to be open sourced completely to the public but that is probably a couple months from now and is a separate project I am pursuing.

**Comment by Onek8** [comment]
Sorry if this was confusing, generally speaking I am building a shop for multiple vendors who provide the same format file of products through a single embeddable portal and no administration in regards to payments or billing information which is handled directly via paypal for each vendor to track. In our case for users who would want to sell a commercial asset not just something listed as free like the entire example repo, we would probably host the file for them (also verify its not malware) and via paypal success return will trigger a temporary hashed download link. For example.

**Comment by Onek8** [comment]
The server will basically have the rust binary running and sftp access for the guys helping the community users like Quantum and timodriaan as well. This way people who have questions about the assets can also receive help from them directly. Two or more people should verify or approve community assets, in some sort of process prior to being added I think.

**Comment by Onek8** [comment]
¯\_(ツ)_/¯

**Comment by Onek8** [comment]
¯\_(ツ)_/¯

**Comment by Onek8** [comment]
'''¯\_(ツ)_/¯'''

**Comment by MoritzBrueckner** [comment]
> and timodriaan as well. This way people who have questions about the assets can also receive help from them directly.

Hi, just a little heads-up: I will not spend time maintaining the marketplace or doing tech support for it or anything similar. I already have enough work to do with other Armory stuff that somehow needs to fit in my free time which I partly sacrifice for Armory, and I'm not really in favor of having a marketplace anyways like I already wrote on Discord (I don't mind though if someone else takes care of it :)).

**Comment by Onek8** [comment]
Ah sorry for bringing you into the discussion, I didnt know you were not in favor of the asset store. I also have a multi vendor system ready to roll out where everyone maintains their own billing, support tickets ect for their customers so no one is burdened but the vendor himself. I may even just add the support tickets and billing UI to the rust shop, so well just stay tuned on discord then and make sure this shop is only a positive thing for everyone

**Pull request merged**
