### PR TITLE
Proposed Changes #4

### PR DESCRIPTION
**Pull request by rpaladin**
# Full Bootstrap Migration
* Mass changes are based on a full [Bootstrap](https://getbootstrap.com) framework migration, _not_ [UIkit](https://getuikit.com) framework. The current website uses UIkit from 2016 and it's time to move on to a more modern framework.

# New
* Features page.
* FAQ page.
* Theme toggle.
* Searchbar (currently only returns the forum search results).
* Global mobile responsiveness.
* Global URL anchor support (if page size is long enough), including implementation of #21.
* And much, much more.

# Website Preview
* Bootstrap: https://rpaladin.github.io

# Questions for Lubos
* The JQuery code in my PR build says it doesn't have access to your JavaScript script at your GitLab repository.<br />Did you accidentally make your repo private?

image

* Some questions regarding all of your softwares & websites privacy statements. ArmorPaint have [this](https://armorpaint.org/privacy) and ArmorLab has [this](https://armorlab.org/privacy). However, aren't some of the 3rd-party links such as Gumroad, itch.io and perhaps even some of the external social links using analytics for statistical purposes? Does that mean those statements are still valid, as it only pertains to software / content you made? What about Armory3D? Can it have it's own privacy page as well?

# Credits

Specials thanks to @MoritzBrueckner | @QuantumCoderQC | @Naxela | @knowledgenude | @longpinkytoes | @1K8 | @Exceptional-3D | other awesome community members for providing content, suggestions, ideas, feedback and motivation. Really appreciate it!

### CODE REVIEW

**Comment by rpaladin** [comment]
Hello @luboslenco, this PR is fully ready to be merged now! Tested with several awesome teammates with different browsers & devices. Two things I would like to request along with a merge:
* If you have time, would you be willing to answer the questions I asked in my initial post. Thanks!
* If possible, would it be alright if I was given some collaborator rights for this repository? It's quite likely I didn't catch something that can be easily fixed later on, and I know how busy you are and I don't wish to waste any more of your time then needed. Note: I'll continue to create new pull-requests for new content. I'd only use the collaborator rights for minor things like typos or fixing broken images and such.

**Comment by rpaladin** [comment]
I forgot to mention, this month's release notes are already prepared and merged into this migration thanks to @ Naxela. He won't be making a separate PR this month.

Lubos, can you confirm this PR is ready to merge?

**Comment by luboslenco** [comment]
Thanks for all the work on this, love the new features page and nicely organized community page!

Right now I find the original theme easier to read - maybe that could be easily addressed by a few tweaks? Like aligning text to the left, cropping images to similar rations, reduce border lines etc. For example there are 4 images displayed for the particles feature, one image per feature should be fine. Some pictures have white borders around them, we can cut those out. Let me know what do you think.

- Will check on the GitLab issue, ideally Gumroad would make it possible to display the sum on its own, but it only allows to show the number of subscribers.
- The privacy policy only mentions ArmorPaint software and I believe it is not linked anywhere on the web. Can add one for the armory3d website as well if needed.
- Added you as a collaborator! 👍

**Comment by rpaladin** [comment]
Hello and you for the feedback! Would it be alright if we went ahead with the merge? I promise I'll be working ASAP on these changes in the days to come.

The thing is the team were waiting for the big announcement of the `2022.09` release for Blender 3.3 LTS support and they relatively need release notes to go along with the announcements. As I mentioned above, Naxela merged this month's release notes into my migration, generously, as we expected this migration to be the new substitute for this month's site.

**Comment by rpaladin** [comment]
Apologies for the open/closing of this PR! My Github client keeps closing the PR when I'm resolving commit conflicts. 😕

**Comment by rpaladin** [comment]
Hi Lubos, I implemented the changes you recommended:
* Removed style borders.
* Cropped images to fixed sizes of `960x540` (w/ release notes it's width `960` / auto height for aspect ratio preservation).
* Fixed image borders.
* Corrected text alignments.

Other changed content:
* Fixed broken release notes (last time, resolve conflicts merged some old notes page).
* Fixed reset navbar - Close forum search icon.
* Fixed some border boundaries with dropdown menus.
* Replaced body font with current Armory site body font.
* Replaced images, globally.
* Improved theme color styling.
* Improved page layouts.
* Improved Node.js script.
* Updated readme.
* Removed FAQ question 2 because Blender 3.3 LTS is now released.

New content:
* `Footer`
  * Back to Top - Button
  * More legal info
  * Individual community links (removed community page link from contact category)
* Asynchronous loading for all images.

# Question for @luboslenco:

* Regarding the homepage background splash image. What do you think is best?
  * Old proposed video? https://rpaladin.github.io/img/home-splash.mp4
    * Good scene complexity, but it somehow doesn't feel fully right to me. What do you think?
  * New proposed video? https://rpaladin.github.io/img/2022-05-b.webp
    * I like this video, because it shows the famous Suzanne, which connects the Blender integration statement with Armory.
  * This image? https://rpaladin.github.io/img/download-fund.webp
    * It looks very good, but it is static, so maybe not the best choice?
   * Maybe you prefer other image or video? Suggestions are fully welcome.

Here is current proposed changes: <https://rpaladin.github.io/>.
And past proposed changes for you to compare by, if needed: <https://arm.oury3d.github.io/>.

**Comment by Naxela** [comment]
@luboslenco @rpaladin Hi, are there plans to merge this or will it be after the next release? I was just wondering which template I should use to write the next release notes with - both are fine with me 🙂

**Comment by rpaladin** [comment]
If Lubos is fine with the latest migration changes (based on his suggestions, listed changelogs above), the migration is fully ready to be merged.

**Comment by luboslenco** [comment]
Thanks for all the great work on this!! It's awesome.

> New proposed video? https://rpaladin.github.io/img/2022-05-b.webp

Looks pretty cool to me. Would be ideal if it's a bit longer & higher res.

Maybe a short excerpt from the fps template would also do: 
https://www.youtube.com/watch?v=zVjk_WOdk2Q

I found one more video, not sure how well it would go with the header but might be worth a try:
https://www.youtube.com/watch?v=MJK03dhJMDI
q

Navigation anim is also cool, just needs a higher res:
https://armory3d.org/img/features-navigation.webp

Feel welcome to pick any variant you like. 🙂

**Pull request merged**
